apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentence-colors
spec:
  selector:
    matchLabels:
      app: sentence-colors
  template:
    metadata:
      labels:
        app: sentence-colors
    spec:
      containers:
        - name: colors
          image: registry.gitlab.com/sentence-app/colors:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PREFIX
              value: "sentence"
            - name: NAMESPACE
              value: "api"
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "25m"
---
apiVersion: v1
kind: Service
metadata:
  name: sentence-colors
spec:
  type: NodePort
  selector:
    app: sentence-colors
  ports:
    - name: http
      port: 80
      targetPort: 8080