apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentence-locations
spec:
  selector:
    matchLabels:
      app: sentence-locations
  template:
    metadata:
      labels:
        app: sentence-locations
    spec:
      containers:
        - name: locations
          image: registry.gitlab.com/sentence-app/locations:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PREFIX
              value: "sentence"
            - name: NAMESPACE
              value: "default"
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "25m"
---
apiVersion: v1
kind: Service
metadata:
  name: sentence-locations
spec:
  type: ClusterIP
  selector:
    app: sentence-locations
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentence-adjectives
spec:
  selector:
    matchLabels:
      app: sentence-adjectives
  template:
    metadata:
      labels:
        app: sentence-adjectives
    spec:
      containers:
        - name: adjectives
          image: registry.gitlab.com/sentence-app/adjectives:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PREFIX
              value: "sentence"
            - name: NAMESPACE
              value: "default"
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "25m"
---
apiVersion: v1
kind: Service
metadata:
  name: sentence-adjectives
spec:
  type: ClusterIP
  selector:
    app: sentence-adjectives
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentence-animals
spec:
  selector:
    matchLabels:
      app: sentence-animals
  template:
    metadata:
      labels:
        app: sentence-animals
    spec:
      containers:
        - name: animals
          image: registry.gitlab.com/sentence-app/animals:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PREFIX
              value: "sentence"
            - name: NAMESPACE
              value: "default"
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "25m"
---
apiVersion: v1
kind: Service
metadata:
  name: sentence-animals
spec:
  type: ClusterIP
  selector:
    app: sentence-animals
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentence-backgrounds
spec:
  selector:
    matchLabels:
      app: sentence-backgrounds
  template:
    metadata:
      labels:
        app: sentence-backgrounds
    spec:
      containers:
        - name: backgrounds
          image: registry.gitlab.com/sentence-app/backgrounds:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PREFIX
              value: "sentence"
            - name: NAMESPACE
              value: "default"
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "25m"
---
apiVersion: v1
kind: Service
metadata:
  name: sentence-backgrounds
spec:
  type: ClusterIP
  selector:
    app: sentence-backgrounds
  ports:
    - name: http
      port: 80
      targetPort: 80